# Generated by Django 6.1 on 2026-08-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="codigo",
            field=models.CharField(max_length=10, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[("B", "Básico"), ("I", "Intermediário"), ("A", "Avançado")],
                default="B",
                max_length=1,
                verbose_name="Nível",
            ),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="data_nascimento",
            field=models.DateField(verbose_name="Data de nascimento"),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="numero_celular",
            field=models.CharField(max_length=14, verbose_name="Número de celular"),
        ),
    ]
