# Generated by Django 6.1 on 2026-08-22 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola", "0003_matricula"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estudante",
            old_name="CPF",
            new_name="cpf",
        ),
        migrations.AlterField(
            model_name="curso",
            name="codigo",
            field=models.CharField(
                max_length=10,
                validators=[django.core.validators.MinLengthValidator(3)],
                verbose_name="Código",
            ),
        ),
        migrations.AlterField(
            model_name="estudante",
            name="cpf",
            field=models.CharField(
                default="00000000000", max_length=11, unique=True, verbose_name="CPF"
            ),
        ),
    ]
